### ISSUE TITLE
Suggestion: Add a subpoint to 90DNS

### ISSUE THREAD

**Issue by Akorax** [AtlasNX/Homebrew-Guide#27]
Superb guide! But as a first time user I were a bit confused by the 90DNS 8th bullet. It sais perform a connection test but it doesn't state that you have to activate the connection (beacuse if you set the connection to not automatically connect it wont do that after you press "save"). Furthermore it doesn't state what the expected result is or what you shouldn't expect it to be.

I therefore suggest that you add to "safetyprecautions.rst" 90DNS 8th bullet something like this:
If you see error code 2160-8007 you have cleared this step successfully. If you see another code you might not have enabled the connection yet. Check the previous X steps and try again.

**Comment by noahc3** [comment]
"Perform the connection test" means hit the "connect to this network button" after you press save, afaik it will never automatically perform the test unless you are adding the network for the first time (which the guide instructs you to do otherwise). I can change the wording.

That said you should not be getting 2160-8007 with 90DNS... the connection test should pass.

**Comment by Akorax** [comment]
It seems I really misunderstood the guide then. I can connect successfully when I hit the "Connect to this network"-button. But then on the previous menu a button named "Test Connection" is now displayed. Hitting that button is what I thought the guide meant by "Perform a connection test".

I recon since I can connect to the internet but get a connection error when I perform the connection test that the DNS is working as intended?

**Comment by noahc3** [comment]
b6d4aecfb54f7eda921784beb04aac4f889ec0e0
